### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by nilskp** [charlieamer/jade-query#1]
Just tried this (0.3.3) and using `//cdn.jsdelivr.net/jade/1.3.1/runtime.min.js`, since the raw github `runtime.js` is no longer available, but I'm getting a `Uncaught TypeError: jade.compile is not a function`.

**Comment by charlieamer** [comment]
it doesnt work because you actually need a whole standalone jade. Latest one seems to be 1.11.0, but for some reason since internationalization in 1.10.0, they don't work in browser anymore, so here's version 1.9.0 i found that works well for me: https://raw.githubusercontent.com/jadejs/jade/1.9.0/jade.js (note: i found it here, in "Browser support" section: https://github.com/jadejs/jade). Please let me know if this works for you

**Comment by nilskp** [comment]
Yep that works, although it's better to use `https://cdnjs.cloudflare.com/ajax/libs/jade/1.9.0/jade.min.js` for correct MIME type.

Will you update the main page?
